### ISSUE TITLE
Error: Please upload PingFirmata to the board

### ISSUE THREAD

**Issue by stevegregorydenver** [ajfisher/nodebots-hcsr04#3]
I am having trouble installing PingFermata to my Arduino Uno R3 board using Interchange 1.0.1.

My project involves capturing data from two ping sensors, and there are no other sensors or actuators connected to the Arduino board, so I think it makes sense to use the "PingFirmata" model rather than the "backpack" model.  I am referring to the diagram and example code at: https://github.com/rwaldron/johnny-five/blob/master/docs/proximity-hcsr04-analog.md

To install PingFirmata I followed these steps:
1. Put Arduino Uno in configuration mode by jumping +5v to D2
2. node_modules.bin\interchange install hc-sr04 -a uno -p COM7 --firmata
3. Remove jumper from D2

These steps appeared to work, i.e.:

```
>node_modules\.bin\interchange install hc-sr04 -a uno -p COM7 --firmata
Installing hc-sr04 from npm
node-socket-test@0.0.1 I:\dev\node-socket-test
+-- nodebots-hcsr04@0.4.1  extraneous (git+https://github.com/ajfisher/nodebots-hcsr04.git#7afd5c28dc9c566148a93d729ab3606cb34a7ed1)
`-- nodebots-interchange@1.0.1  extraneous

npm WARN node-socket-test@0.0.1 No repository field.
npm WARN node-socket-test@0.0.1 No license field.
connected
reset complete.
flashing, please wait...
flash complete.

```

Then I run the example program:

```
>node appdemo.js
1461679622574 Connected COM7
1461679626091 Repl Initialized
>> I:\dev\node-socket-test\node_modules\firmata\lib\firmata.js:1559
    throw new Error("Please upload PingFirmata to the board");
          ^
Error: Please upload PingFirmata to the board
    at Board.pingRead (I:\dev\node-socket-test\node_modules\firmata\lib\firmata.
js:1559:11)
    at Proximity.<anonymous> (I:\dev\node-socket-test\node_modules\johnny-five\l
ib\proximity.js:193:19)
    at Proximity.Controllers.HCSR04.initialize.value (I:\dev\node-socket-test\no
de_modules\johnny-five\lib\proximity.js:199:9)
    at new Proximity (I:\dev\node-socket-test\node_modules\johnny-five\lib\proxi
mity.js:463:10)
    at Board.<anonymous> (I:\dev\node-socket-test\appdemo.js:5:19)
    at Board.emit (events.js:129:20)
    at process._tickDomainCallback (node.js:381:11)

```

Any clues as to what might be going wrong?  Thanks!

**Comment by ajfisher** [comment]
Can you post the app demo code you are using please?

Not sure what's happening but may be something in j5 & this firmata has
drifted.

**Comment by stevegregorydenver** [comment]
```
var five = require("johnny-five");
var board = new five.Board({port:'COM7'});

board.on("ready", function() {
  var proximity = new five.Proximity({
    controller: "HCSR04",
    pin: 7
  });

  proximity.on("data", function() {
    console.log("Proximity: ");
    console.log("  cm  : ", this.cm);
    console.log("  in  : ", this.in);
    console.log("-----------------");
  });

  proximity.on("change", function() {
    console.log("The obstruction has moved.");
  });
});
```

**Comment by ajfisher** [comment]
Weird. What version of Johnny five are you using?

**Comment by stevegregorydenver** [comment]
It's johnny-five@0.9.43

The Arduino Uno R3 is:
VID = 2341
PID = 0043
REV = 0001

**Comment by ajfisher** [comment]
Hmm - very strange. I may not get to this until tomorrow night (have a
couple of deadlines I need to knock over first) but I'm not sure what is
going on here. Will backtrack some code.

**Comment by ajfisher** [comment]
This was an issue with more recent firmata and johnny five drifting. I've finally got to the bottom of that now and will look at a way we can keep firmata and hcsr04 firmata in step with each other properly.

Tested though and this is now working.

**Comment by devnullnor** [comment]
I have the exact same issue noe with johnny-five@0.11.6. What can I do?

**Comment by mhortac** [comment]
I had the same issue. You should do the following

`npm install nodebots-interchange -g`
`interchange install hc-sr04 -a uno -p COM4 --firmata`

Note: COM4 because of **windows**

In your code, something like this:
```
new Proximity({
    controller: "HCSR04",
    pin: 13
});
```

That's all. It worked for me !

**Comment by malko** [comment]
Still in trouble here, got ubuntu 18.04LTS, arduino uno R3, Johnny-five v1.0.0, using the online arduino IDE to upload StandardFirmataPlus.ino to the arduino. I also follow @mhortac advice replacing the port by /dev/ttyACM0 which was the one my arduino was connected to. But got some errors:
```
Installing hc-sr04 from npm
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN proximity-test@0.0.1 No description
npm WARN proximity-test@0.0.1 No repository field.

+ nodebots-hcsr04@0.5.0
added 1 package from 1 contributor and audited 1 package in 4.122s
found 0 vulnerabilities

ReferenceError: manifest is not defined
    at Interchange.download_from_npm (/home/malko/.npm-packages/lib/node_modules/nodebots-interchange/lib/interchange.js:252:48)
    at Interchange.check_firmware (/home/malko/.npm-packages/lib/node_modules/nodebots-interchange/lib/interchange.js:440:10)
    at Interchange.install_firmware (/home/malko/.npm-packages/lib/node_modules/nodebots-interchange/lib/interchange.js:134:10)
    at Command.<anonymous> (/home/malko/.npm-packages/lib/node_modules/nodebots-interchange/bin/cli.js:41:19)
    at Command.listener (/home/malko/.npm-packages/lib/node_modules/nodebots-interchange/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:180:13)
    at Command.parseArgs (/home/malko/.npm-packages/lib/node_modules/nodebots-interchange/node_modules/commander/index.js:654:12)
    at Command.parse (/home/malko/.npm-packages/lib/node_modules/nodebots-interchange/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/malko/.npm-packages/lib/node_modules/nodebots-interchange/bin/cli.js:45:9)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
```
when running my script: 
```
var five = require("johnny-five");
var board = new five.Board();

board.on("ready", function() {
  var proximity = new five.Proximity({
    controller: "HCSR04",
    pin: 7
  });

  proximity.on("data", function() {
    console.log("Proximity: ");
    console.log("  cm  : ", this.cm);
    console.log("  in  : ", this.in);
    console.log("-----------------");
  });

  proximity.on("change", function() {
    console.log("The obstruction has moved.");
  });
});
```
I got some errors too:
```                                             
1541116658598 Available /dev/ttyACM0  
1541116658621 Connected /dev/ttyACM0  
1541116660288 Repl Initialized  
>> /home/malko/node_modules/firmata/lib/firmata.js:1685
    throw new Error("Please upload PingFirmata to the board");
    ^

Error: Please upload PingFirmata to the board
    at Board.pingRead (/home/malko/node_modules/firmata/lib/firmata.js:1685:11)
    at Proximity.<anonymous> (/home/malko/node_modules/johnny-five/lib/proximity.js:215:19)
    at Proximity.value (/home/malko/node_modules/johnny-five/lib/proximity.js:221:9)
    at new Proximity (/home/malko/node_modules/johnny-five/lib/proximity.js:503:10)
    at Board.<anonymous> (/home/malko/Arduino/proximity-test/index.js:13:19)
    at Board.emit (events.js:185:15)
    at Board.emit (domain.js:422:20)
    at process._tickCallback (internal/process/next_tick.js:176:11)
```
